# Site settings
title: Jin's Blog 
description: >- # site description
  Hi, my name is Jin Dong. I am currently a software engineer @Microsoft in Vancouver(and soon in Redmond).
lang: en-US # default lang
timezone: Canada/Pacific # America/New_York
# image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/djdongjin/djdongjin.github.io
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: Jin Dong
  bio: >- # tell to the world
    Hi, my name is Jin Dong. I am currently a software engineer @Microsoft Vancouver(and soon Redmond).
    You can find me <a href="https://github.com/djdongjin" target="_blank" rel="noopener">@github</a>.
  username: djdongjin # general username
  github: djdongjin # github username
  # twitter: twitter_username # twitter username
  # facebook: facebook_username # facebook username
  email: djdongjin@gmail.com
  avatar: /assets/img/avatar.jpg # change with your own avatar

# URL settings
url: "https://djdongjin.github.io/"
baseurl:
permalink: /:title/
google_analytics: # leave it blank if not wish
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 6

# Build settings
# theme: klise
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
