title:              Jin Dong
email:              djdongjin95@gmail.com
description:        Jin's Blog
author:             Jin
baseurl:            "/"
url:                "https://djdongjin.github.io"

# Social Profiles
github_username:    djdongjin
linkedin_username:  jdong95

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
